# Generated by Django 4.1.1 on 2023-04-27 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salono_rezervacijos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslaugosrezervacija',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 22, 23, 6, 239671, tzinfo=datetime.timezone.utc)),
        ),
    ]
