# Generated by Django 4.1.1 on 2023-05-03 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salono_rezervacijos', '0003_alter_paslaugosrezervacija_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslaugosrezervacija',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 17, 24, 3, 723974, tzinfo=datetime.timezone.utc)),
        ),
    ]
